name: CI/CD Pipeline to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js (or any other runtime)
      uses: actions/setup-node@v3
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test

    - name: Package application
      run: npm run build

    - name: Copy files via SSH
      uses: appleboy/scp-action@v0.1.1
      with:
        host: ${{ secrets.AWS_EC2_IP }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        source: "path/to/your/build/*"
        target: "/home/${{ secrets.SSH_USERNAME }}/app/"

    - name: Deploy via SSH
      uses: appleboy/ssh-action@v0.1.1
      with:
        host: ${{ secrets.AWS_EC2_IP }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd /home/${{ secrets.SSH_USERNAME }}/app/
          # Commands to restart your application, e.g., Docker commands, pm2, etc.
          pm2 restart all
